### PR TITLE
PHPStan 2 + GHA CI

### PR DESCRIPTION
**Pull request by Jean85**

### CODE REVIEW

**Comment by Jean85** [comment]
@moufmouf can you review this & enable Github actions?

**Comment by moufmouf** [comment]
Ho, this is super cool! In order to enable Github actions, I have no way but merging a Github actions file into master.
So let's merge this PR. If anything goes wrong with CI, we can fix that in another PR.

Thanks @Jean85 !

**Comment by moufmouf** [comment]
Alright, so we are facing a few issues: https://github.com/thecodingmachine/phpstan-safe-rule/actions/runs/11972945413

Would you mind opening another PR to fix those?

**Comment by Jean85** [comment]
@moufmouf #36 should fix it, in the meantime I also opened #37 for further work.

**Pull request merged**
