### PR TITLE
Support safe ^2.0

### PR DESCRIPTION
**Pull request by dbrekelmans**

### CODE REVIEW

**Review by Jean85 — APPROVED** [review]

**Comment by nealio82** [comment]
WEN MERGE? 😛

**Review by akondas — APPROVED** [review]

**Comment by dbrekelmans** [comment]
@moufmouf Could you take a look when you have time? I'm only a maintainer on the safe repo, not on this one :)

**Review by Jean85 — APPROVED** [review]
Just updated to this alongside safe 2.0.2, it seems to work.

**Review by KevinVanSonsbeek — APPROVED** [review]

**Comment by dbrekelmans** [comment]
I've created a release on my fork for anyone to use until this PR is merged: 

- https://github.com/dbrekelmans/phpstan-safe-rule/releases/tag/v1.2.0
- https://packagist.org/packages/dbrekelmans/phpstan-safe-rule


If you use this, please take into consideration that I will abandon/remove the fork as soon as this PR is merged.

**Comment by webard** [comment]
@dbrekelmans you have error in your fork in `FunctionsListLoader.php`, method should `getFunctionList` be:
```php
 public static function getFunctionList(): array
    {
        if (self::$functions === null) {
            if (\file_exists(__DIR__.'/../../../safe/generated/functionsList.php')) {
                $functions = require __DIR__.'/../../../safe/generated/functionsList.php';
            } elseif (\file_exists(__DIR__.'/../../../../../vendor/thecodingmachine/safe/generated/functionsList.php')) {
                $functions = require __DIR__.'/../../../../../vendor/thecodingmachine/safe/generated/functionsList.php';
            } else {
                throw new \RuntimeException('Could not find thecodingmachine/safe\'s functionsList.php file.');
            }
            // Let's index these functions by their name
            self::$functions = \Safe\array_combine($functions, $functions);
        }
        return self::$functions;
    }
```

**Comment by dbrekelmans** [comment]
@webard I'm not sure what you mean... I didn't change anything in my fork except for merging this PR.

https://github.com/dbrekelmans/phpstan-safe-rule/blob/v1.2.0/src/Utils/FunctionListLoader.php

**Comment by webard** [comment]
@dbrekelmans thecodingmachine/safe and thecodingmachine/phpstan-safe-rule are in same directory. in vendor. Your package is in dbrekelmans/phpstan-safe-rule, so you need change path relativity in function `getFunctionList`.

**Comment by dbrekelmans** [comment]
@webard Ah I see what you mean, thanks for the heads up. I don't have time to fix it myself today, but if you are willing to create a PR, I can merge and release it

**Comment by moufmouf** [comment]
Hey @dbrekelmans,

I'm really sorry I only see this now.
Of course, if you are maintainer on Safe you also need to be maintainer on this package. I added you as a maintainer right now.

**Comment by dbrekelmans** [comment]
No problem @moufmouf, thanks for adding me as a maintainer!

**Pull request merged**
